### PR TITLE
cluster can only be upgraded if it has transitioned

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards: https://github.com/giantswarm/giantswarm/issues/12641

### CODE REVIEW

**Comment by calvix** [comment]
My only concern is there a chance that some cluster that has broken status would be blocked for an update,  not sure if there is such cluster ATM, but it might be something to announce at least o SEs.

**Comment by anvddriesch** [comment]
That is a good point.
Maybe we can block this only for customers?

**Comment by njuettner** [comment]
We might shoot ourself in the foot, because I'd assume we have currently a lot of clusters which do net have set the right cluster condition and still have only updating as the latest condition. We could try to identify how much we currently have.
Not sure TBH.

**Comment by xh3b4sd** [comment]
+1 on collecting the numbers to see how much of a hustle this would be. The change in general makes kind of sense. Though I agree with the concerns raised.

**Comment by anvddriesch** [comment]
Actually, clusters with the cluster status problem should not be an issue here. In their case, the condition `updating` can not be set for a second time. That means they stay in condition `updated` from the previous update and thus will not be blocked here.

The problem we could see would be with clusters that are stuck in updating. In that case we can not roll back the update or change to another version. This also applies to cluster stuck in creating.

**Comment by njuettner** [comment]
> Actually, clusters with the cluster status problem should not be an issue here. In their case, the condition `updating` can not be set for a second time. That means they stay in condition `updated` from the previous update and thus will not be blocked here.

IIRC we identified clusters staying in `updating` with getting set the `updated` condition or am I wrong?

**Comment by anvddriesch** [comment]
We may have clusters like that but then it would not be related to the recent issues with the status. The main symptom we saw there was the lack of inhibition, which resulted from the lack of an `updating` condition being set.

**Review by njuettner — APPROVED** [review]
not blocking

**Comment by anvddriesch** [comment]
Let's have this for the customers at first and later extend to us. The reason is that I don't want this to annoy us while we are on the hive sprint next month.

**Pull request merged**
