### PR TITLE
add scrape annotation to service template

### PR DESCRIPTION
**Pull request by xh3b4sd**
We want to scrape our admission controller. I am not sure if this is everything we need. Does anyone know if there is more to it? Do we have to do any fancy thing in `g8s-prometheus` or `prometheus-config-controller`?

### CODE REVIEW

**Comment by njuettner** [comment]
I guess we need to expose the default metrics, which is not yet in place: https://prometheus.io/docs/guides/go-application/#how-go-exposition-works

**Comment by xh3b4sd** [comment]
So far all microservices had this builtin because we used `microkit`. I am not sure why this one here should be different.

**Comment by njuettner** [comment]
Then let's followup on this. I will try to create a new PR with microkit. Not blocking you here

**Review by njuettner — APPROVED** [review]

**Review by anvddriesch — APPROVED** [review]

**Comment by anvddriesch** [comment]
I think this should already work. It could be that we also have to define the metrics port but if it's the default that shouldn't be needed.

**Comment by xh3b4sd** [comment]
The project does not use the `microkit` package and it does also not use the prometheus client packages. There is no metrics endpoint defined. I am not sure how this should work as of now. I will merge this PR and then we need to follow up on this still. I tried running the binary locally but couldn't because of all kinds of missing flags and expectations the microservice apparently has about its process environment.

**Pull request merged**
